title: Nitesh Kumar
logo: /assets/img/NiteshKumar.jpg
description: IT professional with an attitude of continuous learning. Experienced in crafting robust and scalable IT solutions with expertise in Java, Python, and SQL. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
