title: Nitesh Kumar
logo: /assets/img/NiteshKumar.jpg
description: IT professional with 4+ Years of Expertise.Java, Python, SQL, GIT, AI and ML. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
