title: Nitesh Kumar
logo: /assets/img/NiteshKumar.jpg
description: Java Developer with a curiosity to learn and on a journey towards AI and ML. With over 4+ Years of IT experience i want to thrive for the best in terms knowledge and hard work.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
